version: '2'

services:
  web:
    image: nginx
    volumes:
      - "./web/contents:/usr/share/nginx/html"

  proxy:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
